# Generated by Django 5.0.6 on 2024-07-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
